version: '3.9'
services:
  myapp:
    depends_on:
    - placement
    networks:
    - dapr-network
    image: ${myImage.name}
  myapp_dapr:
    depends_on:
    - myapp
    image: daprio/daprd:edge
    command:
    - ./daprd
    - -app-id
    - myapp
    - -app-port
    - port
    - -placement-host-address
    - placement:50006
    - air
    network_mode: service:myapp
  myappbis:
    image: ${myImage.name}
  placement:
    networks:
    - dapr-network
    image: daprio/dapr
    ports:
    - 5006:5006
    command:
    - ./placement
    - -port
    - '50006'
networks:
  dapr-network:
    driver: default
