version: '3.9'
services:
  remix:
    depends_on:
    - placement
    networks:
    - dapr-network
    image: node12
    ports:
    - 8000:8000
  remix_dapr:
    depends_on:
    - remix
    image: daprio/daprd:edge
    command:
    - ./daprd
    - -app-id
    - remix
    - -app-port
    - '8000'
    - -placement-host-address
    - placement:50006
    - air
    network_mode: service:remix
  placement:
    networks:
    - dapr-network
    image: daprio/dapr
    ports:
    - 50006:50006
    command:
    - ./placement
    - -port
    - '50006'
networks:
  dapr-network: {}
