version: '3.9'
services:
  myapp:
    depends_on:
    - placement
    networks:
    - dapr-network
    image: myapp
    ports:
    - 80:8000
  myapp_dapr:
    depends_on:
    - myapp
    image: daprio/daprd:edge
    command:
    - ./daprd
    - -app-id
    - myapp
    - -app-port
    - '8000'
    - -placement-host-address
    - placement:50006
    - air
    network_mode: service:myapp
  myappbis:
    image: myappbis
    ports:
    - 80:80
  some-app:
    image: some-app
    ports:
    - 3000:3000
  placement:
    networks:
    - dapr-network
    image: daprio/dapr
    ports:
    - 50006:50006
    command:
    - ./placement
    - -port
    - '50006'
networks:
  dapr-network: {}
